default-category: "main"
categories:
  - id: "main"
    type: "categories"
    categories:
      - "test"
    gui:
      title: "&8RecipeBook | Page &6%page%"
      mask:
        items:
          - black_stained_glass_pane
        pattern:
          - "111111111"
          - "1iiiiiii1"
          - "1iiiiiii1"
          - "1iiiiiii1"
          - "111010111"
      buttons:
        next-page:
          item:
            active: orange_stained_glass_pane name:"&aNext page"
            inactive: gray_stained_glass_pane name:"&7Next page"
          lore:
            active: [ ]
            inactive: [ ]
          row: 5
          column: 6
        prev-page:
          item:
            active: orange_stained_glass_pane name:"&aPrevious page"
            inactive: gray_stained_glass_pane name:"&7Previous page"
          lore:
            active: [ ]
            inactive: [ ]
          row: 5
          column: 4
  - id: "test"
    icon:
      item: "diamond_sword name:\"&6Test Category\""
      lore:
        - ""
        - "&fThis is a test category"
        - ""
        - "&bLeft Click &fto show category items"
        - ""
    type: "items"
    namespaces:
      - "ecoitems"
    keys:
      - "test"
    items:
      - "diamond_block"
    gui:
      title: "&8Test Category | Page &6%page%"
      mask:
        items:
          - black_stained_glass_pane
        pattern:
          - "111111111"
          - "1iiiiiii1"
          - "1iiiiiii1"
          - "1iiiiiii1"
          - "111010111"
      buttons:
        back:
          row: 5
          column: 5
          item: barrier name:"&cBack"
          lore: [ ]
        next-page:
          item:
            active: orange_stained_glass_pane name:"&aNext page"
            inactive: gray_stained_glass_pane name:"&7Next page"
          lore:
            active: [ ]
            inactive: [ ]
          row: 5
          column: 6
        prev-page:
          item:
            active: orange_stained_glass_pane name:"&aPrevious page"
            inactive: gray_stained_glass_pane name:"&7Previous page"
          lore:
            active: [ ]
            inactive: [ ]
          row: 5
          column: 4
        slot:
          lore:
            - ""
            - "&bLeft Click&f to see the recipe"
            - ""
craft-gui:
  title: "&8Crafting Recipe"
  mask:
    items:
      - black_stained_glass_pane
    pattern:
      - "111111111"
      - "1iii11111"
      - "1iii11o11"
      - "1iii11111"
      - "111010111"
  buttons:
    back:
      row: 5
      column: 5
      item: barrier name:"&cBack"
      lore: []