folia-supported: true
name: ${pluginName}
version: ${version}
main: com.mystipixel.recipebook.RecipeBookPlugin
api-version: 1.17
authors: [ _Joogie_ ]
depend:
  - eco
commands:
  recipebook:
    description: Base Command
    permission: recipebook.command.recipebook
    aliases: [ rbook ]